// Rendus produits officiels, servis depuis GitHub via le CDN jsDelivr.
// Genere automatiquement - ne pas editer a la main.
// Depot : https://github.com/fresnelbusiness/phone-photos-cdn

export const PHOTO_CDN = 'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main';

/** Toutes les photos disponibles par modele (la premiere est la principale). */
export const PHONE_PHOTOS: Record<string, string[]> = {
  "Infinix Note Edge 5G": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/infinix-note-edge-5g/infinix-note-edge-5g-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/infinix-note-edge-5g/infinix-note-edge-5g-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/infinix-note-edge-5g/infinix-note-edge-5g-03.png',
  ],
  "Infinix Smart 20": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/infinix-smart-20/infinix-smart-20-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/infinix-smart-20/infinix-smart-20-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/infinix-smart-20/infinix-smart-20-03.png',
  ],
  "Redmi 15C": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-15c/redmi-15c-08.png',
  ],
  "Redmi A3 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a3-pro/redmi-a3-pro-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a3-pro/redmi-a3-pro-02.png',
  ],
  "Redmi A7 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-a7-pro/redmi-a7-pro-08.png',
  ],
  "Redmi Note 14 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-14-pro/redmi-note-14-pro-08.png',
  ],
  "Redmi Note 15 Pro Plus": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-15-pro-plus/redmi-note-15-pro-plus-08.png',
  ],
  "Redmi Note 17": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17/redmi-note-17-08.png',
  ],
  "Redmi Note 17 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/redmi-note-17-pro/redmi-note-17-pro-08.png',
  ],
  "Samsung Galaxy A06": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a06/samsung-galaxy-a06-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a06/samsung-galaxy-a06-02.png',
  ],
  "Samsung Galaxy A07": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a07/samsung-galaxy-a07-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a07/samsung-galaxy-a07-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a07/samsung-galaxy-a07-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a07/samsung-galaxy-a07-04.png',
  ],
  "Samsung Galaxy A17": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a17/samsung-galaxy-a17-08.png',
  ],
  "Samsung Galaxy A26": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a26/samsung-galaxy-a26-07.png',
  ],
  "Samsung Galaxy A56": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-a56/samsung-galaxy-a56-07.png',
  ],
  "Samsung Galaxy S21 FE": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s21-fe/samsung-galaxy-s21-fe-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s21-fe/samsung-galaxy-s21-fe-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s21-fe/samsung-galaxy-s21-fe-03.png',
  ],
  "Samsung Galaxy S22 Plus": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s22-plus/samsung-galaxy-s22-plus-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s22-plus/samsung-galaxy-s22-plus-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s22-plus/samsung-galaxy-s22-plus-03.png',
  ],
  "Samsung Galaxy S23": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23/samsung-galaxy-s23-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23/samsung-galaxy-s23-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23/samsung-galaxy-s23-03.png',
  ],
  "Samsung Galaxy S23 Plus": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23-plus/samsung-galaxy-s23-plus-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23-plus/samsung-galaxy-s23-plus-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23-plus/samsung-galaxy-s23-plus-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s23-plus/samsung-galaxy-s23-plus-04.png',
  ],
  "Samsung Galaxy S25 Plus": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-plus/samsung-galaxy-s25-plus-08.png',
  ],
  "Samsung Galaxy S25 Ultra": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s25-ultra/samsung-galaxy-s25-ultra-08.png',
  ],
  "Samsung Galaxy S26 Ultra": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-s26-ultra/samsung-galaxy-s26-ultra-08.png',
  ],
  "Samsung Galaxy Tab A11": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-tab-a11/samsung-galaxy-tab-a11-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-tab-a11/samsung-galaxy-tab-a11-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-tab-a11/samsung-galaxy-tab-a11-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-tab-a11/samsung-galaxy-tab-a11-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-tab-a11/samsung-galaxy-tab-a11-05.png',
  ],
  "Samsung Galaxy Z Fold 6": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-6/samsung-galaxy-z-fold-6-08.png',
  ],
  "Samsung Galaxy Z Fold 7": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/samsung-galaxy-z-fold-7/samsung-galaxy-z-fold-7-08.png',
  ],
  "TECNO Camon 50": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50/tecno-camon-50-08.png',
  ],
  "TECNO Camon 50 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-50-pro/tecno-camon-50-pro-08.png',
  ],
  "TECNO Camon Slim": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-camon-slim/tecno-camon-slim-08.png',
  ],
  "TECNO Pop 20": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/tecno-pop-20/tecno-pop-20-08.png',
  ],
  "iPhone 11": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11/iphone-11-black-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11/iphone-11-green-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11/iphone-11-purple-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11/iphone-11-red-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11/iphone-11-white-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11/iphone-11-yellow-2019.png',
  ],
  "iPhone 11 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11-pro-max/iphone-11-pro-max-gold-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11-pro-max/iphone-11-pro-max-gold-2019-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11-pro-max/iphone-11-pro-max-silver-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11-pro-max/iphone-11-pro-max-space-2019.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11-pro-max/iphone-11-pro-max-silver-2019-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-11-pro-max/iphone-11-pro-max-space-2019-2.png',
  ],
  "iPhone 12": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12/iphone-12-black-2020.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12/iphone-12-blue-2020.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12/iphone-12-green-2020.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12/iphone-12-purple-2021.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12/iphone-12-red-2020.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12/iphone-12-white-2020.png',
  ],
  "iPhone 12 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro/iphone-12-pro-blue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro/iphone-12-pro-gold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro/iphone-12-pro-graphite.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro/iphone-12-pro-silver.png',
  ],
  "iPhone 12 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro-max/iphone-12-pro-max-blue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro-max/iphone-12-pro-max-gold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro-max/iphone-12-pro-max-graphite.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-12-pro-max/iphone-12-pro-max-silver.png',
  ],
  "iPhone 13": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13/iphone-13-blue-2021.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13/iphone-13-green.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13/iphone-13-midnight-2021.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13/iphone-13-pink-2021.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13/iphone-13-starlight-2021.png',
  ],
  "iPhone 13 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro/iphone-13-pro-blue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro/iphone-13-pro-gold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro/iphone-13-pro-graphite.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro/iphone-13-pro-green.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro/iphone-13-pro-silver.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro/iphone-13-pro-product-red-2021.png',
  ],
  "iPhone 13 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro-max/iphone-13-pro-max-blue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro-max/iphone-13-pro-max-gold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro-max/iphone-13-pro-max-graphite.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro-max/iphone-13-pro-max-green.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-13-pro-max/iphone-13-pro-max-silver.png',
  ],
  "iPhone 14": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14/iphone-14-blue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14/iphone-14-midnight.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14/iphone-14-purple.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14/iphone-14-starlight.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14/iphone-14-yellow.png',
  ],
  "iPhone 14 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro/iphone-14-pro-deeppurple.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro/iphone-14-pro-gold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro/iphone-14-pro-silver.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro/iphone-14-pro-spaceblack.png',
  ],
  "iPhone 14 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro-max/iphone-14-pro-max-deeppurple.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro-max/iphone-14-pro-max-gold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro-max/iphone-14-pro-max-silver.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-14-pro-max/iphone-14-pro-max-spaceblack.png',
  ],
  "iPhone 15": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15/iphone-15-black.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15/iphone-15-blue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15/iphone-15-green.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15/iphone-15-pink.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15/iphone-15-yellow.png',
  ],
  "iPhone 15 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro/iphone-15-pro-blacktitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro/iphone-15-pro-bluetitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro/iphone-15-pro-naturaltitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro/iphone-15-pro-whitetitanium.png',
  ],
  "iPhone 15 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro-max/iphone-15-pro-max-blacktitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro-max/iphone-15-pro-max-bluetitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro-max/iphone-15-pro-max-naturaltitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-15-pro-max/iphone-15-pro-max-whitetitanium.png',
  ],
  "iPhone 16": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16/iphone-16-black.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16/iphone-16-pink.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16/iphone-16-teal.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16/iphone-16-ultramarine.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16/iphone-16-white.png',
  ],
  "iPhone 16 Plus": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-plus/iphone-16-plus-black.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-plus/iphone-16-plus-pink.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-plus/iphone-16-plus-teal.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-plus/iphone-16-plus-ultramarine.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-plus/iphone-16-plus-white.png',
  ],
  "iPhone 16 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro/iphone-16-pro-blacktitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro/iphone-16-pro-deserttitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro/iphone-16-pro-naturaltitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro/iphone-16-pro-whitetitanium.png',
  ],
  "iPhone 16 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro-max/iphone-16-pro-max-blacktitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro-max/iphone-16-pro-max-deserttitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro-max/iphone-16-pro-max-naturaltitanium.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16-pro-max/iphone-16-pro-max-whitetitanium.png',
  ],
  "iPhone 16e": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16e/iphone-16e-black.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16e/iphone-16e-white.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16e/iphone-16e-black-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-16e/iphone-16e-white-dos.png',
  ],
  "iPhone 17": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-black.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-lavender.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-mistblue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-sage.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-white.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-black-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-black-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-lavender-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-lavender-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-mistblue-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-mistblue-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-sage-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-sage-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-white-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17/iphone-17-white-profil.png',
  ],
  "iPhone 17 Air": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-cloudwhite.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-lightgold.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-skyblue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-spaceblack.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-cloudwhite-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-cloudwhite-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-lightgold-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-lightgold-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-skyblue-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-skyblue-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-spaceblack-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-air/iphone-17-air-spaceblack-profil.png',
  ],
  "iPhone 17 Pro": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-pro/iphone-17-pro-cosmicorange.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-pro/iphone-17-pro-deepblue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-pro/iphone-17-pro-silver.png',
  ],
  "iPhone 17 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-pro-max/iphone-17-pro-max-cosmicorange.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-pro-max/iphone-17-pro-max-deepblue.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-17-pro-max/iphone-17-pro-max-silver.png',
  ],
  "iPhone 18 Pro Max": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-standard.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-burgundy.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-glacier.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-standard-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black-3.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-burgundy-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-glacier-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver-3.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-burgundy-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-burgundy-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-glacier-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-glacier-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver-dos.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver-profil.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black-dos-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-black-profil-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-burgundy-dos-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-burgundy-profil-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-glacier-dos-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-glacier-profil-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver-dos-2.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/apple/iphone-18-pro-max/iphone-18-pro-max-silver-profil-2.png',
  ],
  "itel A200": [
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-01.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-02.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-03.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-04.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-05.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-06.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-07.png',
    'https://cdn.jsdelivr.net/gh/fresnelbusiness/phone-photos-cdn@main/android/itel-a200/itel-a200-08.png',
  ],
};

/** Photo principale d'un modele, ou undefined si le modele est inconnu. */
export const getPhoto = (model: string): string | undefined =>
  PHONE_PHOTOS[model]?.[0];

/** Toutes les photos d'un modele (coloris et angles). */
export const getPhotos = (model: string): string[] =>
  PHONE_PHOTOS[model] ?? [];
